drop table if exists collect_history CASCADE;

 create table collect_history (
       collect_history_id bigint generated by default as identity,
        can_count integer default 0 not null,
        collect_time timestamp,
        image_count integer default 0 not null,
        notes clob,
        quantaty integer default 0 not null,
        customer_id bigint,
        primary key (collect_history_id)
    );

 drop table if exists collect_image_meta CASCADE;

 create table collect_image_meta (
       collect_image_meta_id bigint generated by default as identity,
        create_time timestamp,
        image_format varchar(255),
        modified_time timestamp,
        name varchar(255),
        collect_history_id bigint,
        primary key (collect_image_meta_id)
    );

drop table if exists customer CASCADE;

 create table customer (
       customer_id bigint generated by default as identity,
        contract_date date,
        locale varchar(255),
        name varchar(255),
        owner_name varchar(255),
        primary key (customer_id)
    );


 alter table collect_history
       add constraint FKgdr1u3acgacmnwlha2kgjhan9
       foreign key (customer_id)
       references customer;

 alter table collect_image_meta
       add constraint FKjelio6p66e1djg3odi2v9xayi
       foreign key (collect_history_id)
       references collect_history;